[build]
builder = "nixpacks"
buildCommand = "yarn run build"
watchPatterns = ["src/**"]

[deploy]
startCommand = "yarn run start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"
restartPolicyMaxRetries = 5
