name: 🏗️ deploy terraform

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - sandbox
          - prod

permissions:
  id-token: write

jobs:
  plan:
    uses: iccowan/personal_website/.github/workflows/tf-plan.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
      TF_BACKEND_ROLE_ARN: ${{ secrets.TF_BACKEND_ROLE_ARN }}

  approve:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}-tf-approval
    needs: plan

    steps:
      - run: echo "Approved to apply terraform changes to ${{ inputs.environment }}"

  apply:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: approve
    env:
      TF_VAR_ENV: ${{ vars.TF_VAR_ENV || '' }}

    steps:
      - name: 🗃️ checkout code
        uses: actions/checkout@v4

      - name: 🔐 configure aws credentials
        uses: ./.github/actions/setup-tf-aws-credentials-action
        with:
          TF_ROLE_ARN: ${{ secrets.TF_ROLE_ARN }}
          TF_BACKEND_ROLE_ARN: ${{ secrets.TF_BACKEND_ROLE_ARN }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: 🔧 setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: 🟢 terraform init
        run: |
          cd terraform
          terraform init

      - name: 🏗️ terraform apply
        run: |
          cd terraform
          terraform workspace select ${{ inputs.environment }}
          terraform apply -auto-approve

