name: ⚙️ deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
          - sandbox
          - prod

  push:
    branches:
      - main

jobs:
  sandbox:
    uses: iccowan/personal_website/.github/workflows/deploy-to-s3.yml@main
    with:
      environment: 'sandbox'
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

    if: ${{ github.event.inputs.environment == 'sandbox' }}

  staging:
    uses: iccowan/personal_website/.github/workflows/deploy-to-s3.yml@main
    with:
      environment: 'prod'
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

    if: ${{ github.event.inputs.environment == 'prod' || (github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch') }}

